#!/usr/bin/env python3
"""
Daily Blog Idea Generator for Asymmetrical Collage

Reads recent blog posts, uses Claude API to generate 3 new post ideas,
and sends them via Gmail.
"""

import os
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from pathlib import Path
import anthropic


def get_recent_posts(articles_dir: Path, count: int = 10) -> list[dict]:
    """Read the most recent blog posts."""
    posts = []

    for filepath in sorted(articles_dir.glob("*.md"), reverse=True):
        if filepath.name.startswith("_"):
            continue

        content = filepath.read_text(encoding="utf-8")

        # Parse front matter
        if content.startswith("---"):
            parts = content.split("---", 2)
            if len(parts) >= 3:
                front_matter = parts[1].strip()
                body = parts[2].strip()

                # Extract title and summary from front matter
                title = ""
                summary = ""
                tags = ""
                for line in front_matter.split("\n"):
                    if line.startswith("title:"):
                        title = line.replace("title:", "").strip().strip('"')
                    elif line.startswith("summary:"):
                        summary = line.replace("summary:", "").strip().strip('"')
                    elif line.startswith("tags:"):
                        tags = line.replace("tags:", "").strip()

                posts.append({
                    "filename": filepath.name,
                    "title": title,
                    "summary": summary,
                    "tags": tags,
                    "body": body[:500]  # First 500 chars of body
                })

        if len(posts) >= count:
            break

    return posts


def read_context_file(scripts_dir: Path) -> str:
    """Read the blog context file."""
    context_file = scripts_dir / "blog_context.md"
    if context_file.exists():
        return context_file.read_text(encoding="utf-8")
    return ""


def generate_ideas(recent_posts: list[dict], context: str) -> str:
    """Use Claude API to generate blog post ideas."""
    client = anthropic.Anthropic()

    # Format recent posts for the prompt
    posts_summary = "\n\n".join([
        f"**{p['title']}**\nTags: {p['tags']}\nSummary: {p['summary']}\nExcerpt: {p['body'][:200]}..."
        for p in recent_posts[:10]
    ])

    prompt = f"""You are a creative writing assistant for the blog "Asymmetrical Collage."

## Blog Context
{context}

## Recent Posts (to avoid repetition)
{posts_summary}

## Your Task
Generate 3 unique blog post ideas that:
1. Fit the blog's themes and writing style
2. Are NOT similar to recent posts listed above
3. Have a counterintuitive or inverted angle
4. Are actionable and memorable

For each idea, provide:
- **Title:** A compelling, concise title
- **Summary:** One sentence for the RSS feed (mirrors the core insight)
- **Tags:** 3-4 relevant tags from the suggested list
- **Hook:** The opening paragraph (2-3 sentences that grab attention)
- **Core Insight:** The main point to develop (1-2 sentences)
- **Closing:** A suggested ending question or call-to-action

Format your response clearly with "## Idea 1:", "## Idea 2:", "## Idea 3:" headers."""

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=2000,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    return message.content[0].text


def send_email(ideas: str, recipient: str, sender: str, password: str):
    """Send the ideas via Gmail SMTP."""
    today = datetime.now().strftime("%B %d, %Y")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Daily Blog Ideas - {today}"
    msg["From"] = sender
    msg["To"] = recipient

    # Plain text version
    text_content = f"""Daily Blog Ideas for Asymmetrical Collage
Generated on {today}

{ideas}

---
Generated by your daily blog idea automation.
"""

    # HTML version (for better formatting)
    html_content = f"""
<html>
<head>
<style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 700px; margin: 0 auto; padding: 20px; }}
    h1 {{ color: #05445E; border-bottom: 2px solid #189AB4; padding-bottom: 10px; }}
    h2 {{ color: #189AB4; margin-top: 30px; }}
    strong {{ color: #05445E; }}
    .tags {{ background: #f0f7f9; padding: 5px 10px; border-radius: 15px; font-size: 0.9em; display: inline-block; margin: 5px 0; }}
    .section {{ margin-left: 15px; margin-bottom: 10px; }}
    hr {{ border: none; border-top: 1px solid #ddd; margin: 30px 0; }}
    .footer {{ color: #888; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>Daily Blog Ideas</h1>
<p><em>Generated on {today} for Asymmetrical Collage</em></p>

{ideas.replace(chr(10), '<br>').replace('## ', '<h2>').replace('**', '<strong>').replace('</strong>:', ':</strong>')}

<hr>
<p class="footer">Generated by your daily blog idea automation.</p>
</body>
</html>
"""

    msg.attach(MIMEText(text_content, "plain"))
    msg.attach(MIMEText(html_content, "html"))

    # Send via Gmail SMTP
    context = ssl.create_default_context()
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
        server.login(sender, password)
        server.sendmail(sender, recipient, msg.as_string())

    print(f"Email sent successfully to {recipient}")


def main():
    # Get environment variables
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    gmail_address = os.environ.get("GMAIL_ADDRESS")
    gmail_password = os.environ.get("GMAIL_APP_PASSWORD")

    if not all([api_key, gmail_address, gmail_password]):
        raise ValueError("Missing required environment variables: ANTHROPIC_API_KEY, GMAIL_ADDRESS, GMAIL_APP_PASSWORD")

    # Set up paths
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent
    articles_dir = repo_root / "content" / "articles"

    print("Reading recent blog posts...")
    recent_posts = get_recent_posts(articles_dir)
    print(f"Found {len(recent_posts)} recent posts")

    print("Reading blog context...")
    context = read_context_file(script_dir)

    print("Generating blog ideas with Claude...")
    ideas = generate_ideas(recent_posts, context)
    print("Ideas generated successfully")

    print("Sending email...")
    send_email(ideas, gmail_address, gmail_address, gmail_password)

    print("Done!")


if __name__ == "__main__":
    main()
